const DB_KEY='todotak_v8_todo_style';
const $=(s,p=document)=>p.querySelector(s); const $$=(s,p=document)=>[...p.querySelectorAll(s)];
let db=loadDB(); let view='home'; let query=''; let sheetMode='task'; let editId=null; let notified={};
const fa=n=>String(n??'').replace(/[0-9]/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const en=s=>String(s??'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function today(){return new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()).replace(/\u200e/g,'').replace(/-/g,'/');}
function nowTime(){const d=new Date(); return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function save(){localStorage.setItem(DB_KEY,JSON.stringify(db));}
function loadDB(){try{const r=localStorage.getItem(DB_KEY); if(r)return JSON.parse(r)}catch(e){} return {users:['محمدرضا','مدیر کارخانه','فروش','اداری'], tasks:[
 {id:uid(),title:'پیگیری بار آلومینیوم گمرک',desc:'',date:today(),time:'',person:'محمدرضا',list:'Inbox',done:false,created:Date.now()},
 {id:uid(),title:'پیگیری ارز خریداری شده',desc:'',date:today(),time:'',person:'محمدرضا',list:'Inbox',done:false,created:Date.now()},
 {id:uid(),title:'پیگیری و تعیین تکلیف پول برداشت شده بیمه',desc:'',date:today(),time:'',person:'محمدرضا',list:'Inbox',done:false,created:Date.now()},
 {id:uid(),title:'تمدید ضمانت نامه های بارها',desc:'',date:today(),time:'',person:'محمدرضا',list:'Inbox',done:false,created:Date.now()},
 {id:uid(),title:'پیگیری ارز گرفته شده که چرا تو سیستم ثبت نشده بانک صنعت و معدن',desc:'',date:today(),time:'',person:'محمدرضا',list:'Inbox',done:false,created:Date.now()},
 {id:uid(),title:'امضا پروفرما خانم اشراقی',desc:'',date:today(),time:'',person:'محمدرضا',list:'Inbox',done:false,created:Date.now()},
 {id:uid(),title:'ثبت سفارش ها اصلاح شود بارهایی که ارز آن گرفته شده',desc:'',date:today(),time:'',person:'محمدرضا',list:'Inbox',done:false,created:Date.now()}
], reports:[]};}
function isToday(x){return x.date===today();}
function isLate(x){return !x.done && x.date && x.date!==today() && x.date < today();}
function shortDate(d){if(!d)return 'No date'; if(d===today())return 'Today'; return fa(d.split('/').slice(1).join('/'));}
function headerTitle(){return view==='home'?'Today':view==='tasks'?'All':'گزارش من';}
function filteredTasks(){let arr=[...db.tasks]; if(view==='home')arr=arr.filter(t=>!t.done && isToday(t)); if(query.trim()){let q=query.trim(); arr=arr.filter(t=>(t.title+t.desc+t.person+t.list+t.date+t.time).includes(q));} return arr.sort((a,b)=>(a.done-b.done)||((a.date||'9999').localeCompare(b.date||'9999'))||((a.time||'99:99').localeCompare(b.time||'99:99'))||(b.created-a.created));}
function filteredReports(){let arr=[...db.reports]; if(query.trim()){let q=query.trim(); arr=arr.filter(r=>(r.text+r.date+r.type).includes(q));} return arr.sort((a,b)=>b.created-a.created);}
function stats(){return {open:db.tasks.filter(t=>!t.done).length,today:db.tasks.filter(t=>!t.done&&isToday(t)).length,late:db.tasks.filter(isLate).length,done:db.tasks.filter(t=>t.done).length};}
function render(){const app=$('#app'); app.className='app'; app.innerHTML=`
<header class="header">
  <button class="header-icon" id="menuBtn">☰</button>
  <div class="header-title">${esc(headerTitle())}</div>
  <button class="icon-pill" id="notifyBtn">💡</button>
  <button class="header-icon" id="moreBtn">⋮</button>
</header>
${view==='home'?homeHTML():view==='tasks'?tasksHTML():reportsHTML()}
<button class="fab" id="fab">+</button>
<nav class="bottom-nav">
  <button class="nav-btn ${view==='home'?'active':''}" data-view="home"><span class="ico">⌂</span><span>خانه</span></button>
  <button class="nav-btn ${view==='tasks'?'active':''}" data-view="tasks"><span class="ico">✓</span><span>وظایف</span></button>
  <button class="nav-btn ${view==='reports'?'active':''}" data-view="reports"><span class="ico">▣</span><span>گزارش من</span></button>
</nav>
<div class="sheet-bg" id="sheetBg"></div><div class="toast" id="toast"></div>
<div class="menu-panel" id="menuPanel"><div class="menu-box"><button id="exportBtn">کپی خروجی JSON</button><button id="clearDoneBtn">حذف انجام‌شده‌ها</button><button id="closeMenuBtn">بستن</button></div></div>
`; bind();}
function homeHTML(){let s=stats(); return `<div class="top-card"><div class="stat-grid"><div class="stat"><b>${fa(s.open)}</b><span>باز</span></div><div class="stat"><b>${fa(s.today)}</b><span>امروز</span></div><div class="stat"><b>${fa(s.late)}</b><span>عقب‌افتاده</span></div><div class="stat"><b>${fa(s.done)}</b><span>انجام</span></div></div></div><div class="section-title">وظایف امروز</div>${taskPanel(filteredTasks())}<div class="section-title">گزارش امروز</div>${reportList(db.reports.filter(r=>r.date===today()))}`;}
function tasksHTML(){return `<input class="search" id="search" placeholder="جستجو در وظایف..." value="${esc(query)}">${taskPanel(filteredTasks(),'TODAY')}`;}
function reportsHTML(){return `<input class="search" id="search" placeholder="جستجو در گزارش من..." value="${esc(query)}">${reportList(filteredReports())}`;}
function taskPanel(rows,label='TODAY'){return `<div class="todo-panel"><div class="group-head"><span>${label}</span><span class="group-count">${fa(rows.length)}⌄</span></div>${rows.length?rows.map(taskRow).join(''):`<div class="empty">وظیفه‌ای وجود ندارد.</div>`}</div>`;}
function taskRow(t){return `<div class="task-row" data-id="${t.id}"><button class="check ${t.done?'done':''}" data-done="${t.id}">${t.done?'✓':''}</button><div class="task-content"><div class="task-title ${t.done?'done':''}" data-edit="${t.id}">${esc(t.title)}</div>${t.desc?`<div class="task-desc">${esc(t.desc)}</div>`:''}<div class="task-meta"><span class="task-date">${shortDate(t.date)}${t.time?' • '+fa(t.time):''}</span><span class="task-box">${esc(t.list||'Inbox')}</span></div><div class="task-person">${esc(t.person||'محمدرضا')}</div></div></div>`;}
function reportList(rows){if(!rows.length)return `<div class="empty">گزارشی وجود ندارد.</div>`;return `<div class="report-list">${rows.map(r=>`<div class="report-card"><div class="report-meta"><span>${esc(r.type||'عمومی')}</span><span>${esc(shortDate(r.date))}</span></div><div class="report-text">${esc(r.text)}</div><div class="report-actions"><button class="small-btn" data-edit-report="${r.id}">ویرایش</button><button class="small-btn danger" data-del-report="${r.id}">حذف</button></div></div>`).join('')}</div>`;}
function bind(){ $$('.nav-btn').forEach(b=>b.onclick=()=>{view=b.dataset.view;query='';render()}); $('#fab').onclick=()=>openSheet(view==='reports'?'report':'task'); $('#notifyBtn').onclick=requestNotif; $('#moreBtn').onclick=()=>$('#menuPanel').classList.add('show'); $('#menuBtn').onclick=()=>toast('منوی اصلی در نسخه بعدی اضافه می‌شود'); $('#closeMenuBtn').onclick=()=>$('#menuPanel').classList.remove('show'); $('#menuPanel').onclick=e=>{if(e.target.id==='menuPanel')e.currentTarget.classList.remove('show')}; $('#exportBtn').onclick=()=>{navigator.clipboard?.writeText(JSON.stringify(db,null,2)); toast('JSON کپی شد')}; $('#clearDoneBtn').onclick=()=>{db.tasks=db.tasks.filter(t=>!t.done);save();render()}; const s=$('#search'); if(s)s.oninput=e=>{query=e.target.value; render()}; $$('[data-done]').forEach(b=>b.onclick=e=>{e.stopPropagation(); const t=db.tasks.find(x=>x.id===b.dataset.done); t.done=!t.done; t.doneAt=t.done?Date.now():null; save(); render();}); $$('[data-edit]').forEach(el=>el.onclick=()=>openSheet('task',el.dataset.edit)); $$('[data-edit-report]').forEach(b=>b.onclick=()=>openSheet('report',b.dataset.editReport)); $$('[data-del-report]').forEach(b=>b.onclick=()=>{db.reports=db.reports.filter(r=>r.id!==b.dataset.delReport);save();render()});}
function openSheet(mode,id=null){sheetMode=mode;editId=id; const bg=$('#sheetBg'); const item=mode==='task'?(db.tasks.find(t=>t.id===id)||{}):(db.reports.find(r=>r.id===id)||{}); bg.classList.add('show'); bg.innerHTML=`<div class="sheet"><input class="sheet-main" id="mainInput" placeholder="${mode==='task'?'چه کاری باید انجام شود؟':'گزارش را بنویس...'}" value="${esc(mode==='task'?(item.title||''):(item.text||''))}" autofocus>${mode==='task'?`<textarea class="sheet-desc" id="descInput" placeholder="توضیح">${esc(item.desc||'')}</textarea>`:''}<div class="sheet-options" id="options"><div class="inline"><label class="field">تاریخ<input id="dateInput" value="${esc(item.date||today())}"></label><label class="field">ساعت<input id="timeInput" type="time" value="${esc(item.time||'')}"></label></div>${mode==='task'?`<div class="inline"><label class="field">مسئول<select id="personInput">${db.users.map(u=>`<option ${u===(item.person||'محمدرضا')?'selected':''}>${esc(u)}</option>`).join('')}</select></label><label class="field">لیست<select id="listInput"><option ${item.list==='Inbox'?'selected':''}>Inbox</option><option ${item.list==='Factory'?'selected':''}>Factory</option><option ${item.list==='Office'?'selected':''}>Office</option></select></label></div>`:`<label class="field">نوع گزارش<select id="typeInput"><option>عمومی</option><option>تولید</option><option>فروش</option><option>اداری</option></select></label>`}</div><div class="sheet-tools"><button class="tool" id="dateTool">▦</button><button class="tool" id="personTool">⚑</button><button class="tool" id="tagTool">◇</button><button class="tool" id="moreTool">•••</button><button class="save-circle" id="saveSheet">➜</button></div></div>`; setTimeout(()=>$('#mainInput')?.focus(),50); bg.onclick=e=>{if(e.target===bg)closeSheet()}; $('#dateTool').onclick=$('#personTool').onclick=$('#tagTool').onclick=$('#moreTool').onclick=()=>$('#options').classList.toggle('show'); $('#saveSheet').onclick=saveSheet;}
function closeSheet(){editId=null; $('#sheetBg').classList.remove('show'); $('#sheetBg').innerHTML='';}
function saveSheet(){const main=$('#mainInput').value.trim(); if(!main){toast('متن را بنویس');return} if(sheetMode==='task'){let t=db.tasks.find(x=>x.id===editId); if(!t){t={id:uid(),done:false,created:Date.now()}; db.tasks.unshift(t)} Object.assign(t,{title:main,desc:$('#descInput').value.trim(),date:$('#dateInput').value.trim()||today(),time:$('#timeInput').value,person:$('#personInput').value,list:$('#listInput').value,updated:Date.now()});}else{let r=db.reports.find(x=>x.id===editId); if(!r){r={id:uid(),created:Date.now()}; db.reports.unshift(r)} Object.assign(r,{text:main,date:$('#dateInput').value.trim()||today(),time:$('#timeInput').value,type:$('#typeInput').value,updated:Date.now()});} save(); closeSheet(); render();}
function toast(t){const el=$('#toast'); if(!el)return; el.textContent=t; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),1800)}
async function requestNotif(){if(!('Notification' in window)){toast('این مرورگر نوتیفیکیشن ندارد');return}let p=Notification.permission;if(p!=='granted')p=await Notification.requestPermission();toast(p==='granted'?'نوتیفیکیشن فعال شد':'اجازه داده نشد')}
function checkDue(){if(!('Notification' in window)||Notification.permission!=='granted')return; const d=today(), tm=nowTime(); db.tasks.forEach(t=>{if(t.done||!t.time||t.date!==d||t.time!==tm)return; const k=t.id+'_'+d+'_'+tm; if(notified[k])return; notified[k]=1; new Notification('TodoTak',{body:t.title,tag:k});});}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{}); setInterval(checkDue,30000); render();
