const DB_KEY='tak_duty_control_v5_real_redesign';
const SESSION_KEY='tak_duty_user_v5';
const $=s=>document.querySelector(s);
const app=document.getElementById('app');
let db=loadDB();
let view='home', filter='open', q='', rq='', editingTask=null, editingReport=null;
let notified={};

const fa=n=>String(n).replace(/[0-9]/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const en=s=>String(s||'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d));
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
function today(){return norm(new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()).replace(/\u200e/g,''));}
function norm(v){v=en(v).trim().replace(/-/g,'/').replace(/\./g,'/');let m=v.match(/^(\d{4})\/(\d{1,2})\/(\d{1,2})$/);if(!m)return'';return `${m[1]}/${String(+m[2]).padStart(2,'0')}/${String(+m[3]).padStart(2,'0')}`}
function showDate(v){let n=norm(v);if(!n)return fa(v||'');let [y,m,d]=n.split('/');return fa(`${y}/${+m}/${+d}`)}
function shortDate(v){let n=norm(v);if(!n)return'بدون تاریخ';let [y,m,d]=n.split('/');if(n===today())return'امروز';return fa(`${+m}/${+d}`)}
function nowTime(){let d=new Date();return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function nowStamp(){return `${showDate(today())} ${fa(nowTime())}`}
function save(){localStorage.setItem(DB_KEY,JSON.stringify(db))}
function loadDB(){try{let r=localStorage.getItem(DB_KEY);if(r)return JSON.parse(r)}catch(e){}return seed()}
function seed(){return {users:[{id:'u_admin',name:'محمدرضا',role:'مدیرعامل'},{id:'u_factory',name:'مدیر کارخانه',role:'مدیر کارخانه'},{id:'u_sales',name:'فروش',role:'کارشناس فروش'}],currentUser:'u_admin',tasks:[
{id:'t1',title:'پیگیری بار آلومینیوم گمرک',desc:'تماس با ترخیص‌کار و گرفتن آخرین وضعیت بار.',userId:'u_admin',type:'date',status:'open',date:today(),hasTime:true,time:'10:30',createdAt:nowStamp()},
{id:'t2',title:'ثبت سفارش ها اصلاح شود بارهایی که ارز آن گرفته شده',desc:'در سیستم ثبت سفارش، مواردی که ارز گرفته‌اند مشخص شوند.',userId:'u_admin',type:'forward',status:'open',date:'',hasTime:false,time:'',createdAt:nowStamp()}
],reports:[]}}
function user(){return db.users.find(x=>x.id===(localStorage.getItem(SESSION_KEY)||db.currentUser||'u_admin'))||db.users[0]}
function username(id){return db.users.find(x=>x.id===id)?.name||'محمدرضا'}
function visibleTasks(){let t=[...db.tasks]; if(q.trim()){let s=q.trim().toLowerCase();t=t.filter(x=>(x.title+x.desc+username(x.userId)+x.status+x.type+x.date+x.time).toLowerCase().includes(s))} if(view==='tasks'){if(filter==='open')t=t.filter(x=>x.status!=='done'); if(filter==='today')t=t.filter(x=>x.status!=='done'&&x.date===today()); if(filter==='late')t=t.filter(isLate); if(filter==='done')t=t.filter(x=>x.status==='done')} return t.sort((a,b)=>sortKey(a).localeCompare(sortKey(b)))}
function sortKey(t){if(t.status==='done')return '9'+(t.doneAt||''); if(t.type==='forward')return '2'+(t.createdAt||''); return '1'+(t.date||'9999')+(t.time||'99:99')}
function isLate(t){return t.status!=='done'&&t.type!=='forward'&&t.date&&t.date<today()}
function stats(){let all=db.tasks;return {open:all.filter(x=>x.status!=='done').length,today:all.filter(x=>x.status!=='done'&&x.date===today()).length,late:all.filter(isLate).length,done:all.filter(x=>x.status==='done').length}}

function render(){app.className='app';app.innerHTML=`
<header class="top"><div class="top-row"><button class="icon" id="menuBtn">☰</button><h1>${viewTitle()}</h1><button class="icon" id="notifBtn">💡</button></div><div class="sub-head">${esc(user().name)} • ${esc(user().role)}</div></header>
<div class="drawer-bg" id="drawerBg"></div><aside class="drawer" id="drawer"><div class="profile"><b>TAK Duty</b><span>${esc(user().name)} • نسخه ساده و سریع</span></div>${drawerBtn('home','خانه')}${drawerBtn('tasks','وظایف من')}${drawerBtn('reports','گزارش من')}<button id="notifMenu">فعال‌سازی نوتیفیکیشن</button><button id="exportBtn">خروجی پشتیبان</button></aside>
<main class="content">${view==='home'?homeHTML():view==='tasks'?tasksHTML():reportsHTML()}</main>
<button class="fab" id="fab">+</button><nav class="nav"><button data-v="home" class="${view==='home'?'active':''}"><i>⌂</i><span>خانه</span></button><button data-v="tasks" class="${view==='tasks'?'active':''}"><i>☑</i><span>وظایف</span></button><button data-v="reports" class="${view==='reports'?'active':''}"><i>▣</i><span>گزارش</span></button></nav>
<div class="modal-bg" id="modalBg"></div><div class="menu" id="actionMenu"></div><div class="toast" id="toast"></div>`;bind()}
function viewTitle(){return view==='home'?'Today':view==='tasks'?'وظایف من':'گزارش من'}
function drawerBtn(v,t){return `<button data-v="${v}" class="${view===v?'active':''}">${t}</button>`}
function homeHTML(){let s=stats();return `<div class="summary"><button class="sum" data-go="open"><b>${fa(s.open)}</b><span>باز</span></button><button class="sum" data-go="today"><b>${fa(s.today)}</b><span>امروز</span></button><button class="sum" data-go="late"><b>${fa(s.late)}</b><span>عقب‌افتاده</span></button><button class="sum" data-go="done"><b>${fa(s.done)}</b><span>انجام</span></button></div><section class="panel"><div class="panel-title"><h2>وظایف من</h2><button class="mini-btn" data-open="task">وظیفه جدید</button></div><input class="search" id="homeSearch" placeholder="جستجو در وظایف..." value="${esc(q)}">${taskList(db.tasks.filter(x=>x.status!=='done').slice(0,8))}</section><section class="panel"><div class="panel-title"><h2>گزارش من</h2><button class="mini-btn" data-open="report">گزارش جدید</button></div>${reportList(db.reports.filter(r=>r.userId===user().id).slice(0,5))}</section>`}
function tasksHTML(){let s=stats();return `<div class="summary"><button class="sum ${filter==='open'?'active':''}" data-filter="open"><b>${fa(s.open)}</b><span>باز</span></button><button class="sum ${filter==='today'?'active':''}" data-filter="today"><b>${fa(s.today)}</b><span>امروز</span></button><button class="sum ${filter==='late'?'active':''}" data-filter="late"><b>${fa(s.late)}</b><span>عقب‌افتاده</span></button><button class="sum ${filter==='done'?'active':''}" data-filter="done"><b>${fa(s.done)}</b><span>انجام</span></button></div><section class="panel"><input class="search" id="taskSearch" placeholder="مثلاً: ارز، گمرک، محمدرضا..." value="${esc(q)}">${taskList(visibleTasks())}</section>`}
function reportsHTML(){let rows=db.reports.filter(r=>r.userId===user().id||user().id==='u_admin');if(rq.trim()){let s=rq.trim();rows=rows.filter(r=>(r.text+r.type+r.date+username(r.userId)).includes(s))}return `<section class="panel"><div class="panel-title"><h2>گزارش من</h2><button class="mini-btn" data-open="report">ثبت گزارش</button></div><input class="search" id="reportSearch" placeholder="جستجو در گزارش‌ها..." value="${esc(rq)}">${reportList(rows)}</section>`}
function taskList(rows){if(!rows.length)return `<div class="empty">وظیفه‌ای وجود ندارد.</div>`;return `<div class="task-list">${rows.map(taskHTML).join('')}</div>`}
function taskHTML(t){let done=t.status==='done', late=isLate(t), typ=t.type==='forward'?'پیشرو':t.type==='daily'?'روزانه':'تاریخ‌دار';return `<div class="task"><button class="check ${done?'done':''}" data-done="${t.id}" title="انجام شد"></button><div class="task-body"><div class="task-title">${esc(t.title)}</div>${t.desc?`<div class="task-desc">${esc(t.desc)}</div>`:''}<div class="meta"><span class="badge ${t.date===today()?'today':''}">${shortDate(t.date)}</span>${t.hasTime?`<span class="badge today">${fa(t.time)}</span>`:''}<span class="badge ${done?'done':late?'late':'open'}">${done?'انجام شد':late?'عقب‌افتاده':'باز'}</span><span class="badge ${t.type==='forward'?'forward':''}">${typ}</span><span class="badge">${esc(username(t.userId))}</span><button class="more" data-more="${t.id}">⋮</button></div></div></div>`}
function reportList(rows){if(!rows.length)return `<div class="empty">گزارشی وجود ندارد.</div>`;return rows.sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||'')).map(r=>`<div class="report"><div class="report-top"><b>${esc(r.type||'عمومی')}</b><span>${showDate(r.date)} • ${esc(username(r.userId))}</span></div><div class="report-text">${esc(r.text)}</div><div class="actions"><button class="btn gray" data-edit-report="${r.id}">ویرایش</button><button class="btn danger" data-del-report="${r.id}">حذف</button></div></div>`).join('')}
function bind(){
 $('#menuBtn').onclick=()=>{$('#drawer').classList.add('show');$('#drawerBg').classList.add('show')}; $('#drawerBg').onclick=closeDrawer;
 document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{view=b.dataset.v;closeDrawer();render()});
 document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{filter=b.dataset.go;view='tasks';render()});
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});
 document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openModal(b.dataset.open));
 $('#fab').onclick=()=>openModal(view==='reports'?'report':'task');
 $('#notifBtn').onclick=requestNotif; $('#notifMenu').onclick=requestNotif;
 $('#exportBtn').onclick=()=>{navigator.clipboard?.writeText(JSON.stringify(db,null,2));toast('پشتیبان JSON کپی شد')};
 let hs=$('#homeSearch'); if(hs)hs.oninput=e=>{q=e.target.value;render()}; let ts=$('#taskSearch'); if(ts)ts.oninput=e=>{q=e.target.value;render()}; let rs=$('#reportSearch'); if(rs)rs.oninput=e=>{rq=e.target.value;render()};
 document.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>toggleDone(b.dataset.done));
 document.querySelectorAll('[data-more]').forEach(b=>b.onclick=e=>showMenu(e,b.dataset.more));
 document.querySelectorAll('[data-edit-report]').forEach(b=>b.onclick=()=>{editingReport=db.reports.find(r=>r.id===b.dataset.editReport);openModal('report')});
 document.querySelectorAll('[data-del-report]').forEach(b=>b.onclick=()=>delReport(b.dataset.delReport));
}
function closeDrawer(){$('#drawer')?.classList.remove('show');$('#drawerBg')?.classList.remove('show')}
function toast(t){let el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function showMenu(e,id){let t=db.tasks.find(x=>x.id===id), m=$('#actionMenu');m.innerHTML=`<button data-edit-task="${id}">ویرایش</button><button data-detail-task="${id}">جزئیات</button><button class="danger" data-del-task="${id}">حذف</button>`;m.style.display='block';m.classList.add('show');let r=e.target.getBoundingClientRect();m.style.top=(r.bottom+6)+'px';m.style.left=Math.max(12,r.left-130)+'px';m.querySelector('[data-edit-task]').onclick=()=>{editingTask=t;openModal('task')};m.querySelector('[data-detail-task]').onclick=()=>alert(`${t.title}\n\n${t.desc||''}\n\n${shortDate(t.date)} ${t.hasTime?t.time:''}`);m.querySelector('[data-del-task]').onclick=()=>delTask(id);setTimeout(()=>document.body.onclick=()=>{m.classList.remove('show');m.style.display='none';document.body.onclick=null},50)}
function openModal(kind){let bg=$('#modalBg');bg.classList.add('show');bg.innerHTML=kind==='task'?taskForm():reportForm();$('#closeModal').onclick=closeModal;if(kind==='task'){let ht=$('#hasTime');let tb=$('#timeBox');ht.onchange=()=>tb.style.display=ht.checked?'block':'none';$('#saveTask').onclick=saveTask}else{$('#saveReport').onclick=saveReport}}
function closeModal(){editingTask=null;editingReport=null;$('#modalBg').classList.remove('show');$('#modalBg').innerHTML=''}
function userOptions(sel){return db.users.map(u=>`<option value="${u.id}" ${sel===u.id?'selected':''}>${esc(u.name)}</option>`).join('')}
function taskForm(){let t=editingTask||{title:'',desc:'',userId:user().id,type:'date',date:today(),hasTime:false,time:'09:00'};return `<div class="modal"><h2>${editingTask?'ویرایش وظیفه':'وظیفه جدید'}</h2><div class="grid"><label class="full">عنوان وظیفه<input id="taskTitle" value="${esc(t.title)}" placeholder="مثلاً پیگیری بار آلومینیوم گمرک"></label><label class="full">توضیح<textarea id="taskDesc" placeholder="توضیح اختیاری">${esc(t.desc)}</textarea></label><label>مسئول<select id="taskUser">${userOptions(t.userId)}</select></label><label>نوع<select id="taskType"><option value="date" ${t.type==='date'?'selected':''}>تاریخ مشخص</option><option value="daily" ${t.type==='daily'?'selected':''}>روزانه</option><option value="forward" ${t.type==='forward'?'selected':''}>باید انجام شود / پیشرو</option></select></label><label>تاریخ شمسی<input id="taskDate" value="${esc(t.date||today())}" placeholder="1405/03/09"></label><div class="time-line full"><input type="checkbox" id="hasTime" ${t.hasTime?'checked':''}><label for="hasTime">برای این وظیفه ساعت و نوتیفیکیشن داشته باشد</label></div><label id="timeBox" style="display:${t.hasTime?'block':'none'}">ساعت<input type="time" id="taskTime" value="${esc(t.time||'09:00')}"></label></div><div class="actions"><button class="btn primary" id="saveTask">ثبت</button><button class="btn gray" id="closeModal">بستن</button></div></div>`}
function reportForm(){let r=editingReport||{type:'عمومی',text:'',date:today()};return `<div class="modal"><h2>${editingReport?'ویرایش گزارش':'گزارش جدید'}</h2><div class="grid"><label>تاریخ شمسی<input id="repDate" value="${esc(r.date)}"></label><label>نوع گزارش<select id="repType"><option ${r.type==='عمومی'?'selected':''}>عمومی</option><option ${r.type==='تولید'?'selected':''}>تولید</option><option ${r.type==='فروش'?'selected':''}>فروش</option><option ${r.type==='اداری'?'selected':''}>اداری</option></select></label><label class="full">شرح گزارش<textarea id="repText" placeholder="امروز چه کاری انجام شد؟">${esc(r.text)}</textarea></label></div><div class="actions"><button class="btn primary" id="saveReport">ثبت گزارش</button><button class="btn gray" id="closeModal">بستن</button></div></div>`}
function saveTask(){let title=$('#taskTitle').value.trim();if(!title){toast('عنوان وظیفه را بنویس');return}let item=editingTask||{id:uid('t'),status:'open',createdAt:nowStamp()};Object.assign(item,{title,desc:$('#taskDesc').value.trim(),userId:$('#taskUser').value,type:$('#taskType').value,date:norm($('#taskDate').value)||today(),hasTime:$('#hasTime').checked,time:$('#taskTime')?.value||'',updatedAt:nowStamp()});if(item.type==='forward')item.date='';if(!editingTask)db.tasks.unshift(item);save();closeModal();render();toast('وظیفه ثبت شد')}
function toggleDone(id){let t=db.tasks.find(x=>x.id===id);if(!t)return;t.status=t.status==='done'?'open':'done';t.doneAt=t.status==='done'?nowStamp():'';save();render()}
function delTask(id){if(confirm('وظیفه حذف شود؟')){db.tasks=db.tasks.filter(x=>x.id!==id);save();render()}}
function saveReport(){let text=$('#repText').value.trim();if(!text){toast('متن گزارش را بنویس');return}let r=editingReport||{id:uid('r'),userId:user().id,createdAt:nowStamp()};Object.assign(r,{date:norm($('#repDate').value)||today(),type:$('#repType').value,text,updatedAt:nowStamp()});if(!editingReport)db.reports.unshift(r);save();closeModal();render();toast('گزارش ثبت شد')}
function delReport(id){if(confirm('گزارش حذف شود؟')){db.reports=db.reports.filter(r=>r.id!==id);save();render()}}
async function requestNotif(){if(!('Notification' in window)){toast('این مرورگر نوتیفیکیشن وب را پشتیبانی نمی‌کند');return}let p=Notification.permission;if(p!=='granted')p=await Notification.requestPermission();toast(p==='granted'?'نوتیفیکیشن فعال شد':'اجازه نوتیفیکیشن داده نشد')}
function checkDue(){if(!('Notification' in window)||Notification.permission!=='granted')return;let tm=nowTime(), td=today();db.tasks.filter(t=>t.status!=='done'&&t.hasTime&&t.date===td&&t.time===tm).forEach(t=>{let key=t.id+'_'+td+'_'+tm;if(notified[key])return;notified[key]=true;new Notification('TAK Duty Control',{body:t.title,tag:key});});}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
setInterval(checkDue,30000);
save();render();
